PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, birthday TEXT, age INTEGER, first_visit TEXT, visit_count INTEGER DEFAULT 0, avg_amount REAL DEFAULT 0, total_amount INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS casts (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, joined_year INTEGER);
CREATE TABLE IF NOT EXISTS sales (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, customer_id INTEGER NOT NULL, cast_id INTEGER NOT NULL, amount INTEGER NOT NULL, FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE, FOREIGN KEY (cast_id) REFERENCES casts(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'admin'
);
